"""5 commit

Revision ID: 377e5e706ded
Revises: 7e2f15af1d8e
Create Date: 2022-09-22 10:31:50.266541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377e5e706ded'
down_revision = '7e2f15af1d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
