"""5 commit

Revision ID: 91d1563a4095
Revises: afa732dcb27a
Create Date: 2022-09-22 10:25:43.345791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91d1563a4095'
down_revision = 'afa732dcb27a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phonecode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phonecode', mysql.VARCHAR(length=6), nullable=False))
    # ### end Alembic commands ###
