"""5 commit

Revision ID: 9f94bd6f11c1
Revises: 377e5e706ded
Create Date: 2022-09-22 12:43:49.252708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f94bd6f11c1'
down_revision = '377e5e706ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('user', sa.Column('username', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    op.drop_column('user', 'id')
    # ### end Alembic commands ###
