"""5 commit

Revision ID: e47f8aebd16f
Revises: 38fe86f714d5
Create Date: 2022-09-21 21:55:48.878636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e47f8aebd16f'
down_revision = '38fe86f714d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=64), nullable=False))
    # ### end Alembic commands ###
